# Generated by Django 5.0.1 on 2024-01-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_modified',
        ),
    ]
